# Generated by Django 5.2.13 on 2026-05-03 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_style', models.CharField(choices=[('strict', 'Strict and direct'), ('balanced', 'Slightly supportive but honest'), ('supportive', 'Supportive')], max_length=20)),
                ('detail_level', models.CharField(choices=[('short', 'Short and concise'), ('medium', 'Medium detail'), ('detailed', 'Detailed and step-by-step')], max_length=20)),
                ('primary_goal', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
